# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'React', :path => '../node_modules/react-native'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

target 'ExampleCocoapods' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ExampleCocoapods

  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

  target 'ExampleCocoapodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

